### PR TITLE
Feature Unstranslate Video Mosaic  + Various fixes

### LINKED ISSUE #66: [FEATURE] Untranslate End Screen Mosaic inside the Player
**Describe the bug**
The titles of the suggested videos shown on the end screen are keeping the translated text, instead of displaying the original titles in their source language.

**To Reproduce**
Simply go to the end of any video and check the mosaic with video suggestions and its titles.

**Expected behavior**
Titles on the mosaic should also be "untranslated".

**Screenshots**
Image

**Environment (please complete the following information):**
 - OS: Windows 11
 - Browser: Vivaldi 7.3.3635.12
 - YouTube Anti Translate version: 1.19.0

### LINKED ISSUE #115: [BUG] Title duplication when videos with similar titles watched one immediatly after another
**Describe the bug**

**To Reproduce**

1. Go to https://www.youtube.com/watch?v=PHgc8Q6qTjc&list=RDPHgc8Q6qTjc&start_radio=1 (video with title "Congratulations" with language set to Russian in anonymous mode.
2. In the video suggestions on the right (important), find "Congratulations 2" from "FlyingKitty" and click on it (video https://www.youtube.com/watch?v=ydFJe6WPg-k&list=RDydFJe6WPg-k&start_radio=1)
3. Watch the video for a bit and look at the tab title, it's getting longer and longer, with "2 2 2 2 2 2 2 2 2" series being added periodically, so it is "Congratulations 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 - YouTube" for example.

**Expected behavior**
The tab title stays "Congratulations 2"

**Screenshots**

Image

**Environment (please complete the following information):**

- OS: Linux Mint 22.1
- Browser: Firefox 143
- YouTube Anti Translate version 1.19.10
- YouTube language setting in use: Russian

### LINKED ISSUE #116: [BUG] Unnecessary error 404 network calls to YT oembed API
**Describe the bug**
Requests to oembed on pages which are not "/watch", like so: `GET
https://www.youtube.com/oembed?url=https://www.youtube.com/@PewDiePie/videos
[HTTP/2 404  214ms]`

**To Reproduce**

1. Go to https://www.youtube.com/watch?v=PHgc8Q6qTjc&list=RDPHgc8Q6qTjc&start_radio=1 in Firefox
2. Click on PewdiePie channel name to get to https://www.youtube.com/@PewDiePie
3. Click Videos to get to https://www.youtube.com/@PewDiePie/videos
4. See series of 404 errors:
```
GET
https://www.youtube.com/oembed?url=https://www.youtube.com/@PewDiePie/videos
[HTTP/2 404  107ms]

15:08:17.448
XHRGET
https://www.youtube.com/oembed?url=https://www.youtube.com/@PewDiePie/videos
[HTTP/2 404  103ms]

15:08:17.650
XHRGET
https://www.youtube.com/oembed?url=https://www.youtube.com/@PewDiePie/videos
[HTTP/2 404  110ms]

15:08:17.789
XHRGET
https://www.youtube.com/oembed?url=https://www.youtube.com/@PewDiePie/videos
[HTTP/2 404  56ms]
```
which go on forever.

Clicking on Streams to get to https://www.youtube.com/@PewDiePie/streams also results in 404, but to  
```
XHRGET
https://www.youtube.com/oembed?url=https://www.youtube.com/@PewDiePie/streams
[HTTP/2 404  97ms]
```

**Expected behavior**
These oembed requests are not made.

**Environment (please complete the following information):**

- OS: Linux Min 22.1
- Browser Firefox 143
- YouTube Anti Translate version 1.19.10
- YouTube language setting in use: Russian

### LINKED ISSUE #124: [BUG] Incompatible with 'No YouTube Shorts'
**Describe the bug**
Youtube still translates titles of shorts if I use the 'No YouTube Shorts' addon (to see shorts with the normal video layout).

**To Reproduce**
1. install the '[No YouTube Shorts](https://addons.mozilla.org/en-US/firefox/addon/no-youtube-shorts)' addon
2. enable it, but with the option 'Hide Shorts shelves' unchecked
3. visit a page with several shorts ([e.g.](https://www.youtube.com/@celaalopess/shorts))

**Expected behavior**
Titles should be in the original language, which is Portuguese.

**Screenshots**
Image

**Environment:**
- OS: Windows 10
- Firefox 142.0
- YouTube Anti Translate version 1.19.12
- No YouTube Shorts version 3.0.2
- YouTube language setting in use: English (US)

**Additional context**
If I disable the 'No YouTube Shorts' addon and reload the page, all titles appear with the original language.

### LINKED ISSUE #126: [BUG] Warning: "/browser_specific_settings/gecko/data_collection_permissions" property will be required in Firefox
**Describe the bug**
When publishing my fork, the validator on addons.mozilla.org told me:

```
The "data_collection_permissions" property is missing.

Warning: "/browser_specific_settings/gecko/data_collection_permissions" property will be required in the future. Please add this key to the manifest. More information at: https://mzl.la/blog-data-consent-firefox-nightly
manifest.json
```
The URL redirects to https://blog.mozilla.org/addons/2025/05/09/new-extension-data-consent-experience-now-available-in-firefox-nightly/

I assume we do not collect any data from our users, so this would be appropriate:

```
      "data_collection_permissions": {
        "required": ["none"]
      }
```
I will make a PR shortly

### LINKED ISSUE #128: [BUG]
**Describe the bug**
YouTube Shorts' Titles aren't translating to english: the original language
**To Reproduce**
Click on Shorts and every few shorts (personally it was ~50/50) shorts were in my native language instead of english, the original language

**Expected behavior**
The title should've been english
**Screenshots**
The title is just not english, I don't think i have to provide a screenshot of it
**Environment (please complete the following information):**

- OS: windows 11
- Browser: Brave v1.82.161, Chromium 140.0.7339.80
- YouTube Anti Translate version: 1.19.12
- YouTube language setting in use: Dutch, so the titles should've been english instead of dutch

**Additional context**
-

### LINKED ISSUE #132: [BUG] Title bar and chapter texts still getting translated
**Describe the bug**
Text in the title bar and some sections of the chapter selection still translate

**To Reproduce**

1. Go to YouTube
2. Click on a video that gets automatically translated
3. The name of the video in the tab will be translated and so will be the text in some sections of the chapters

**Expected behavior**
None of the texts would change from one language to another

**Screenshots**

**Environment (please complete the following information):**

- OS: Windows 11 Pro
- Browser: Librefox
- YouTube Anti Translate version 1.19.12
- YouTube language setting in use: Italian

**Additional context**
The only other time I encountered this type of bug in this state with only certain sections were still translating was in previous versions where some videos in the notification tab would not translate, but regarding the current issue, the only times I saw the title in the upper bar and chapter names not translating was when overall the addon could not stop any translation. I made a video showcasing the issue because it would hard to show in just an image that the names of the chapters get translated when moving the cursor, but after less than a second the addon tries to fix this and restores the original text, but this happens every time the cursor moves along the timeline bar, not when keeping it still

https://github.com/user-attachments/assets/c29ce504-666d-4c15-a102-ddd927c679a7

### PR DESCRIPTION
**Pull request by namakeingo**
- Feature Close #66 

- Fix video author translation on videos with multiple authors
- Fix author search result untranslation
- Fix `isVisible` function when any of the parents is invisible
- Fix #116
- Fix #124
- Fix #115 
- Fix #128 
- Fix #132 
- Handle short player description
- Handle fallback to title inside of description
- Include 1 line change of pr #127 - Fix #126

### CODE REVIEW

File: app/src/background.js [hunk 1]
```diff
@@ -352,40 +329,40 @@ async function createOrUpdateUntranslatedFakeNode(
       return;
     }
 
-    const oldTitle = translatedElement?.textContent ?? fakeNode?.textContent;
+    const oldTitle =
```
Comment (zpix1) [inline app/src/background.js]: Maybe simplify it? Looks too hard to read (change ternary into if expression with comment)

File: app/src/global.js [hunk 2]
```diff
@@ -504,6 +506,27 @@ ytm-shorts-lockup-view-model`,
       return false;
     }
 
+    // Check computed style for ancestors
+    // DOM traversal and style computation should not have performance impact but limit to a max depth of 25 to be safe
+    // DevTools Performance analysis shows no time difference with or without this code
```
Comment (zpix1) [inline app/src/global.js:511]: 👍

File: tests/helpers/AuthStorageHelper.ts [hunk 3]
```diff
@@ -20,7 +21,7 @@ import { Page } from "@playwright/test";
  * @returns
  */
 export async function newPageWithStorageStateIfItExists(
-  context,
+  context: any,
```
Comment (zpix1) [inline tests/helpers/AuthStorageHelper.ts]: Playwright should have these types exported, why not use them?

File: tests/helpers/AuthStorageHelper.ts [hunk 4]
```diff
@@ -163,7 +164,7 @@ export async function newPageWithStorageStateIfItExists(
  * @param {Page} page
  * @returns {Locator|null}
  */
-export async function findLoginButton(page) {
+export async function findLoginButton(page: any) {
```
Comment (zpix1) [inline tests/helpers/AuthStorageHelper.ts]: Same here

**Review by zpix1 — APPROVED** [review]
LGTM, despite minor comments.
