### PR TITLE
Fix mobile bugs with titles, description and channel name; fix channel search results untranlation

### LINKED ISSUE #84: [BUG] Channel titles in search are not always correctly untranslated
> Actually mostly fine but channel name is search result is still not handled
> 
> 
>  

 _Originally posted by @namakeingo in [#69](https://github.com/zpix1/yt-anti-translate/issues/69#issuecomment-3126679126)_

### LINKED ISSUE #85: [BUG] Video Titles inside of a Playlist are not untranslated on mobile
**Describe the bug**
Whdn on m.youtube.com the titles of any video inside of a Playlist are not untranslated 

**To Reproduce**
1. Go to any playlist with videos that need untranslating

**Expected behavior**
Video titles inside on the Playlist are untranslated

**Screenshots**

Videos in screenshot are https://m.youtube.com/watch?v=laYESwLMfl4 and https://m.youtube.com/watch?v=FQowxyI1dKg

Or example with a public Playlist https://m.youtube.com/playlist?list=PLoSWVnSA9vG8hI-SUpAimvYJrPh-PRRvp 

**Environment (please complete the following information):**
 - OS: Android 
 - Browser Firefox for Android 140.1
 - YouTube Anti Translate version 1.19.5

**Additional Context**
``` html
<ytm-playlist-video-renderer class="item"><div class="compact-media-item" data-has-subscribe-button="" data-color-palette-applied="false"><a href="/watch?v=UPrkC1LdlLY&amp;list=PLoSWVnSA9vG8hI-SUpAimvYJrPh-PRRvp&amp;index=1&amp;t=324s&amp;pp=iAQB" class="compact-media-item-image" style="" aria-haspopup="false" aria-hidden="true"><ytm-compact-thumbnail class="video-thumbnail-container-compact center video-thumbnail-container-compact-rounded"><div class="cover video-thumbnail-img video-thumbnail-bg"></div><img alt="" class="yt-core-image cover video-thumbnail-img yt-core-image--fill-parent-height yt-core-image--fill-parent-width yt-core-image--content-mode-scale-aspect-fill yt-core-image--loaded" src="https://i.ytimg.com/vi_lc/UPrkC1LdlLY/hqdefault_it.jpg?sqp=&amp;rs=AOn4CLB68DIM_5D0DSq5fbB5XZG5NpJWQg"><div class="video-preview-shim"></div><div class="video-thumbnail-overlay-bottom-group"><ytm-thumbnail-overlay-resume-playback-renderer><div class="thumbnail-overlay-resume-playback-progress" style="width: 16%;"></div></ytm-thumbnail-overlay-resume-playback-renderer><ytm-thumbnail-overlay-time-status-renderer data-style="DEFAULT"><badge-shape class="badge-shape-wiz badge-shape-wiz--thumbnail-default badge-shape-wiz--thumbnail-badge"><div class="badge-shape-wiz__text">32:21</div></badge-shape></ytm-thumbnail-overlay-time-status-renderer></div></ytm-compact-thumbnail></a><div class="compact-media-item-metadata" data-has-badges="false"><a href="/watch?v=UPrkC1LdlLY&amp;list=PLoSWVnSA9vG8hI-SUpAimvYJrPh-PRRvp&amp;index=1&amp;t=324s&amp;pp=iAQB" class="compact-media-item-metadata-content" style="" aria-haspopup="false"><h4 class="compact-media-item-headline" style=""><span class="yt-core-attributed-string yt-core-attributed-string--link-inherit-color" aria-label="Sopravvivi 100 giorni in un bunker antinucleare e vinci 500.000$ di MrBeast 310.242.955 visualizzazioni 11 mesi fa 32 minuti" role="text">Sopravvivi 100 giorni in un bunker antinucleare e vinci 500.000$</span></h4><div class="subhead" style="" aria-hidden="true"><div class="compact-media-item-byline small-text"><span class="yt-core-attributed-string">MrBeast</span></div></div></a><ytm-bottom-sheet-renderer class="compact-media-item-menu"><button class="yt-spec-button-shape-next yt-spec-button-shape-next--text yt-spec-button-shape-next--mono yt-spec-button-shape-next--size-l yt-spec-button-shape-next--icon-button" title="" aria-label="Menu Azione"><div aria-hidden="true" class="yt-spec-button-shape-next__icon"><c3-icon style="width: 24px; height: 24px;" fill-icon="false"><span class="yt-icon-shape yt-spec-icon-shape"><div style="width: 100%; height: 100%; display: block; fill: currentcolor;"><svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" height="24" viewBox="0 0 24 24" width="24" focusable="false" aria-hidden="true" style="pointer-events: none; display: inherit; width: 100%; height: 100%;"><path d="M12 16.5c.83 0 1.5.67 1.5 1.5s-.67 1.5-1.5 1.5-1.5-.67-1.5-1.5.67-1.5 1.5-1.5zM10.5 12c0 .83.67 1.5 1.5 1.5s1.5-.67 1.5-1.5-.67-1.5-1.5-1.5-1.5.67-1.5 1.5zm0-6c0 .83.67 1.5 1.5 1.5s1.5-.67 1.5-1.5-.67-1.5-1.5-1.5-1.5.67-1.5 1.5z"></path></svg></div></span></c3-icon></div><yt-touch-feedback-shape style="border-radius: inherit;"><div aria-hidden="true" class="yt-spec-touch-feedback-shape yt-spec-touch-feedback-shape--touch-response"><div class="yt-spec-touch-feedback-shape__stroke"></div><div class="yt-spec-touch-feedback-shape__fill"></div></div></yt-touch-feedback-shape></button></ytm-bottom-sheet-renderer></div></div></ytm-playlist-video-renderer>
```

### LINKED ISSUE #86: [BUG] Channel Featured video title not untranslated on Mobile
**Describe the bug**
The title of a featured channel video is not untranslated on m.youtube.com

**To Reproduce**
1. Go to a channel page that has a featured video
E.g. https://m.youtube.com/@benio_ASMR/featured

**Expected behavior**
The title of the featured video should be untranslated

**Screenshots**

**Environment (please complete the following information):**
 - OS: Android
 - Browser: Firefox for Android 140.1
 - YouTube Anti Translate version 1.19.5

**Additional context**
``` html
<ytm-channel-featured-video-renderer class="item"><a href="/watch?v=p5u3oqMIu_M" style="" aria-haspopup="false"><ytm-thumbnail-cover class="video-thumbnail-container-large center not-rendered-from-rich-item rounded-thumbnail"><div class="cover video-thumbnail-img video-thumbnail-bg"></div><img alt="" class="yt-core-image cover video-thumbnail-img yt-core-image--fill-parent-height yt-core-image--fill-parent-width yt-core-image--content-mode-scale-aspect-fill yt-core-image--loaded" src="https://i.ytimg.com/vi/p5u3oqMIu_M/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&amp;rs=AOn4CLBdBNkPwekFWD2b4rRV6ka0JwpFDg"><div class="video-preview-shim"></div></ytm-thumbnail-cover><h3 class="details"><span class="yt-core-attributed-string" aria-label="ASMR -2 °C Gioco di ruolo rinfrescante❄️ di benio店長 / ASMR屋さん 629.124 visualizzazioni 3 settimane fa 36 minuti" role="text">ASMR -2 °C Gioco di ruolo rinfrescante❄️</span></h3></a></ytm-channel-featured-video-renderer>
```

### LINKED ISSUE #88: [BUG] Channel name above description not untranslated on Mobile
**Describe the bug**
Channel name above description not untranslated on Mobile

**To Reproduce**
1. Set YouTube language to English
2. Navigate to https://m.youtube.com/watch?v=i7Uu7wxdskg
3. Channel name above description is "CARTONI MORTI | Very Italians Cartoons" instead of "CARTONI MORTI" 

**Expected behavior**
Channel name above description of a video should always be the original channel name

**Screenshots**

**Environment (please complete the following information):**
 - OS: Android
 - Browser: Firefox for Android 140.1 
 - YouTube Anti Translate version 1.19.5

**Additional context**
``` html
<div class="slim-owner-bylines"><h3 class="slim-owner-channel-name" aria-hidden="true"><span class="yt-core-attributed-string">CARTONI MORTI | Very Italian Cartoons</span></h3><div class="subhead" aria-hidden="true"><span class="yt-core-attributed-string" role="text">1.48M</span></div></div>
```

### PR DESCRIPTION
**Pull request by namakeingo**
- Fix #86 
- Fix #85
- Fix #88
- Fix #84
- Fix issue where mobile description could be "untranslated" as the currently playing advert
- Add version PATCH to `publish-firefox.yml` and timeout for human review support
- Add YouTube language setting to `bug_report.md` recommended information

### CODE REVIEW

**Comment by zpix1** [comment]
image

I see channel titles on mobile in search are still translated

File: app/src/background_description.js [hunk 1]
```diff
@@ -623,27 +630,45 @@ function restoreOriginalDescriptionAndAuthor() {
...
+function restoreOriginalAuthorOnly() {
+  const originalAuthor = fetchOriginalAuthor();
+
+  if (!originalAuthor) {
+    return;
+  }
+
+  if (originalAuthor) {
+    handleAuthor(originalAuthor);
+  }
```
[the remark this answers is not in the document]
Comment (zpix1) [reply app/src/background_description.js]: it makes sense actually

File: app/src/global.js [hunk 2]
```diff
@@ -1208,4 +1209,25 @@ ytm-shorts-lockup-view-model`,
...
     return requestPromise;
   },
+
+  /**
+   * Extracts the YouTube video ID from a given URL.
+   * Supports /watch?v=, /shorts/, and full URLs.
+   * @param {string} url
+   * @returns {string|null}
+   */
+  extractVideoIdFromUrl: function (url) {
```
Comment (zpix1) [inline app/src/global.js:1219]: it is duplicated in app/src/background_notifications.js

**Review by zpix1 — APPROVED** [review]
I think it is OK and greatly improves our mobile support. Comments are up to you.

File: app/src/global.js (hunk 2 above)
Comment (namakeingo) [reply app/src/global.js:1219]: I was planning to replace the references inside of `background_notifications`, but then I forgot. Done now
