### PR TITLE
fix: #106, debounce in background is not working

### LINKED ISSUE #106: [BUG] <title> doesn't get untranslated
**Describe the bug**

the tab title stays translated

**To Reproduce**

open any translated video
look at the tab title (translated)
look at the title on youtube (not translated)

**Expected behavior**
the tab title should be untranslated

**Screenshots**

Image

Image

**Environment (please complete the following information):**

- OS: Windows Server 2025 Datacenter
- Google Chrome 139.0.7258.67
- YouTube Anti Translate version 1.19.9
- YouTube language setting in use: Polish (PL)

### PR DESCRIPTION
**Pull request by zpix1**
Closes #106, #112, #108, #109, #110, #105
Looks like new chrome update changed how rAF in background works.

This PR uses setTimeout in background.

How to test:
1. Windows, chrome 139
2. Use EN locale and open this video https://www.youtube.com/watch?v=0xcZ_RdXZSA
3. Open another tab
4. Reload opened video and quickly switch to another tab
5. On 1.19.9 after some time title become english, while on 1.19.10 it will always change to russian one.

### CODE REVIEW

File: app/src/global.js [hunk 1]
```diff
@@ -189,48 +189,102 @@ ytm-shorts-lockup-view-model`,
...
+      if (useRaf) {
+        rafId = requestAnimationFrame((time) => {
+          const now =
+            typeof time === "number"
+              ? time
+              : typeof performance !== "undefined" && performance.now
+                ? performance.now()
+                : Date.now();
+          const elapsed = now - lastExecTime;
+          if (elapsed >= wait) {
```
Comment (namakeingo) [inline app/src/global.js]: I think it would be better to be `(elapsed >= (wait * 1.5))` or `(elapsed >= (wait + 30 /* ms */))` that way requestAnimationFrame timing can still take priority if not too much time passed.
At a typical 60fps each animation frame is at 16.6ms so with the default of 30ms as minimum wait, that would trigger at 33.2ms without this fallback logic, that is most definitely an acceptable range. What we need to detect for fallback is more significant skips.

Comment (zpix1) [reply app/src/global.js]: I changed fix, it should be more clear now

**Comment by zpix1** [comment]
@namakeingo your fix works OK, included it into changelog.

File: app/src/global.js (hunk 1 above)
Comment (namakeingo) [reply app/src/global.js]: Cool stuff `if (document.hidden || typeof requestAnimationFrame === "undefined")` as only condition for fallback makes the logic much more readable indeed. Thank you

File: tests-unit/debounce.test.js [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+describe("YoutubeAntiTranslate.debounce", () => {
+  beforeEach(() => {
+    vi.useFakeTimers();
+    installRAFStub();
+    // Ensure default visibility unless the test overrides it
+    Object.defineProperty(document, "hidden", {
+      value: false,
+      configurable: true,
+    });
+  });
```
Comment (namakeingo) [inline tests-unit/debounce.test.js]: The default should be visibility "visible" given that in the test for foreground activity you are not updating the value, while in the test for background activity you are setting to "hidden"

File: tests-unit/debounce.test.js [hunk 3]
```diff
@@ -0,0 +1,82 @@
...
+    debounced();
+    vi.advanceTimersByTime(15); // half of wait window
+    vi.runOnlyPendingTimers();
+    expect(fn).toHaveBeenCalledTimes(1);
+
+    // After the wait window, the scheduled call should execute
+    vi.advanceTimersByTime(20); // total 35ms > 30ms
+    vi.runOnlyPendingTimers();
+    expect(fn).toHaveBeenCalledTimes(2);
+  });
```
Comment (namakeingo) [inline tests-unit/debounce.test.js:62]: Please add to the test a
``` typescript
    const rafSpy = vi.spyOn(global, "requestAnimationFrame");
    expect(rafSpy).toHaveBeenCalled();
```
That way the unit tests actually verifies that normal operation uses raf
